[build]
command = "pip install --upgrade pip && pip install pipenv && pipenv install && pipenv run start"
publish = "build_directory"  # Cambia esto al directorio donde se publica tu app

[context.production.environment]
PYTHON_VERSION = "3.10"
NETLIFY_VERBOSE = "true"

