[build]
command = "pip install --upgrade pip && pip install -r requirements.txt && gunicorn -b 0.0.0.0:3001 wsgi:app"
publish = "build_directory"

[context.production.environment]
PYTHON_VERSION = "3.8"
NETLIFY_VERBOSE = "true"




